# Generated by Django 4.2 on 2023-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_user', 'super_user'), ('control_project_user', 'control_project_user'), ('control_quality_user', 'quality_control_user'), ('commerce_user', 'commerce_user'), ('procurement_commerce_user', 'procurement_commerce_user'), ('financial_user', 'financial_user'), ('warehouse_user', 'warehouse_user'), ('production_user', 'production_user'), ('technical_user', 'technical_user')], max_length=32),
        ),
    ]
