# Generated by Django 4.2 on 2023-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_user', 'کاربر مدیر'), ('control_project_user', 'کاربر کنترل پروژه'), ('control_quality_user', 'کاربر کنترل کیفی'), ('commerce_user', 'کاربر بازرگانی'), ('procurement_commerce_user', 'کاربر بازرگانی-فروش'), ('financial_user', 'کاربر مالی'), ('warehouse_user', 'کاربر انبار'), ('production_user', 'کابر تولید'), ('technical_user', 'کاربر فنی')], max_length=32),
        ),
    ]
