# Generated by Django 4.1 on 2023-08-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_material_project'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='inquiry_user',
        ),
        migrations.RemoveField(
            model_name='inquirystatus',
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='task',
            name='allocator_department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='allocator_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='InquiryStatus',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
