# Generated by Django 4.2 on 2024-02-07 02:50

import core.mixins
import core.models
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
                ('number_id', models.CharField(default=core.utils.random_int, max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('projects_type', models.CharField(choices=[('selected', 'انتخاب شده'), ('other', 'متفرقه')], max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dep_ticket', to='public.department')),
                ('projects', models.ManyToManyField(to='public.project')),
                ('to_departments', models.ManyToManyField(related_name='to_deps_ticket', to='public.department')),
            ],
            options={
                'ordering': ('-id',),
            },
            bases=(core.mixins.RemoveOldFileMixin, models.Model),
        ),
    ]
