# Generated by Django 4.1 on 2023-08-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_inquiry_from_department'),
        ('notification', '0002_notificationdepartment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdepartment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notificationdepartment',
            name='to_department',
        ),
        migrations.AddField(
            model_name='notificationdepartment',
            name='departments',
            field=models.ManyToManyField(to='public.department'),
        ),
        migrations.AddField(
            model_name='notificationdepartment',
            name='is_all_departments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationdepartment',
            name='is_all_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationdepartment',
            name='is_showing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationdepartment',
            name='projects',
            field=models.ManyToManyField(to='public.project'),
        ),
    ]
