# Generated by Django 4.1 on 2023-10-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notificationdepartment_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationdepartment',
            options={'ordering': ('priority', '-id')},
        ),
    ]
