# Generated by Django 4.2 on 2023-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notificationdepartment_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdepartment',
            name='is_all_departments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationdepartment',
            name='is_all_projects',
            field=models.BooleanField(default=False),
        ),
    ]
