# Generated by Django 4.2 on 2023-11-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notificationdepartment_is_all_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdepartment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
