# Generated by Django 4.2 on 2024-01-30 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0060_projectfile_allocator_user'),
        ('notification', '0009_alter_notificationdepartment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='notificationdepartment',
            name='is_all_projects',
        ),
        migrations.RemoveField(
            model_name='notificationdepartment',
            name='is_showing',
        ),
        migrations.RemoveField(
            model_name='notificationdepartment',
            name='seen',
        ),
        migrations.AddField(
            model_name='notificationdepartment',
            name='to_departments',
            field=models.ManyToManyField(related_name='to_dp_notification', to='public.department'),
        ),
        migrations.CreateModel(
            name='NotificationDepartmentSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.department')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationdepartment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
