# Generated by Django 4.2 on 2024-01-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_remove_notificationdepartment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdepartment',
            name='projects_type',
            field=models.CharField(choices=[('selected', 'انتخاب شده'), ('other', 'متفرقه')], default='other', max_length=10),
            preserve_default=False,
        ),
    ]
