# Generated by Django 4.2 on 2024-01-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_notificationdepartment_projects_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdepartmentseen',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_status', to='notification.notificationdepartment'),
        ),
    ]
