# Generated by Django 4.2 on 2024-01-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_notificationdepartmentseen_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdepartment',
            name='attached_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
