# Generated by Django 4.1 on 2023-08-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_inquiry_from_department'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdepartment',
            name='to_department',
        ),
        migrations.AddField(
            model_name='ticketdepartment',
            name='departments',
            field=models.ManyToManyField(to='public.department'),
        ),
        migrations.AddField(
            model_name='ticketdepartment',
            name='is_all_departments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketdepartment',
            name='is_all_projects',
            field=models.BooleanField(default=True),
        ),
    ]
