# Generated by Django 4.1 on 2023-08-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_ticketdepartment_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdepartment',
            options={'ordering': ('-id',)},
        ),
    ]
