# Generated by Django 4.1 on 2023-10-16 02:37

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_alter_project_description'),
        ('support', '0004_alter_ticketdepartment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
                ('description', models.TextField()),
                ('is_all_departments', models.BooleanField(default=True)),
                ('is_all_projects', models.BooleanField(default=True)),
                ('departments', models.ManyToManyField(to='public.department')),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_from_dp', to='public.department')),
                ('projects', models.ManyToManyField(to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
