# Generated by Django 4.2 on 2023-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='code',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='Report Code'),
        ),
    ]
