# Generated by Django 4.2 on 2023-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_alter_inquiry_state'),
        ('support', '0006_report_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='public.project'),
        ),
    ]
