# Generated by Django 4.2 on 2023-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_alter_inquiry_state'),
        ('support', '0007_alter_report_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='code',
            field=models.CharField(blank=True, default='', max_length=12, unique=True, verbose_name='Report Code'),
        ),
        migrations.AlterField(
            model_name='report',
            name='projects',
            field=models.ManyToManyField(blank=True, to='public.project'),
        ),
    ]
