# Generated by Django 4.2 on 2023-11-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_alter_inquiry_state'),
        ('support', '0011_remove_ticketdepartment_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_departments', to='public.department'),
        ),
    ]
