# Generated by Django 4.2 on 2024-01-29 07:23

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0060_projectfile_allocator_user'),
        ('support', '0012_alter_ticketdepartment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ticketdepartment',
            name='is_all_projects',
        ),
        migrations.RemoveField(
            model_name='ticketdepartment',
            name='seen',
        ),
        migrations.AddField(
            model_name='ticketdepartment',
            name='number_id',
            field=models.CharField(default=core.utils.random_int, max_length=10),
        ),
        migrations.AddField(
            model_name='ticketdepartment',
            name='title',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketdepartment',
            name='to_departments',
            field=models.ManyToManyField(related_name='to_deps_ticket', to='public.department'),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='from_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dep_ticket', to='public.department'),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='projects',
            field=models.ManyToManyField(to='public.project'),
        ),
    ]
