# Generated by Django 4.2 on 2024-01-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_remove_ticketdepartment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdepartment',
            name='projects_type',
            field=models.CharField(choices=[('selected', 'انتخاب شده'), ('other', 'متفرقه')], default='selected', max_length=10),
            preserve_default=False,
        ),
    ]
