# Generated by Django 4.2 on 2024-01-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_ticketdepartment_projects_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
