# Generated by Django 4.1 on 2023-08-16 17:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirystatus',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src),
        ),
    ]
