# Generated by Django 4.1 on 2023-08-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_inquirystatus_file_alter_task_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='allocator_department',
            new_name='to_department',
        ),
        migrations.AddField(
            model_name='task',
            name='from_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_department', to='public.department'),
            preserve_default=False,
        ),
    ]
