# Generated by Django 4.1 on 2023-08-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_rename_allocator_department_task_to_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.task'),
            preserve_default=False,
        ),
    ]
