# Generated by Django 4.1 on 2023-08-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirystatus',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.inquiry'),
        ),
    ]
