# Generated by Django 4.1 on 2023-08-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
