# Generated by Django 4.1 on 2023-08-19 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_projectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='inquiry_user',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='time_submited',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquirystatus',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='public.inquiry'),
        ),
    ]
