# Generated by Django 4.1 on 2023-08-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_alter_inquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='from_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.department'),
            preserve_default=False,
        ),
    ]
