# Generated by Django 4.1 on 2023-10-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_alter_task_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description_allocate',
        ),
        migrations.AlterField(
            model_name='task',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_hour',
            field=models.IntegerField(null=True),
        ),
    ]
