# Generated by Django 4.1 on 2023-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_remove_task_description_allocate_alter_task_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_start',
            field=models.DateField(null=True),
        ),
    ]
