# Generated by Django 4.1 on 2023-10-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_remove_inquiry_time_submited_inquiry_number_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
