# Generated by Django 4.1 on 2023-10-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_alter_projectfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryfile',
            name='name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
