# Generated by Django 4.2 on 2023-11-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_alter_inquiry_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
