# Generated by Django 4.2 on 2023-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_alter_project_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('checking', 'در حال بررسی قبل ساخت'), ('under_construction', 'در حال ساخت'), ('posted', 'ارسال شده'), ('completed', 'تایید و اتمام'), ('paused', 'متوقف شده')], default='under_construction', max_length=20),
        ),
    ]
