# Generated by Django 4.2 on 2023-11-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0031_alter_project_time_end_alter_project_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryfile',
            name='from_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_file', to='public.department'),
        ),
    ]
