# Generated by Django 4.2 on 2023-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0031_alter_project_time_end_alter_project_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state_modify_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
