# Generated by Django 4.2 on 2023-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0032_inquiryfile_from_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state_modify_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
