# Generated by Django 4.2 on 2023-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0034_alter_project_description_alter_project_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='work_hour',
        ),
        migrations.AddField(
            model_name='task',
            name='work_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
