# Generated by Django 4.2 on 2023-11-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0035_remove_task_work_hour_task_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='from_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.department'),
        ),
    ]
