# Generated by Django 4.2 on 2023-11-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0036_projectfile_from_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmaster',
            options={'ordering': ('-id',)},
        ),
    ]
