# Generated by Django 4.2 on 2023-11-22 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0037_alter_taskmaster_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='number_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.taskmaster'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='state',
            field=models.CharField(choices=[('canceled', 'انصراف'), ('waiting_for_price', 'در انتظار قیمت'), ('price_recorded', 'قیمت ارسال شده')], default=('waiting_for_price', 'در انتظار قیمت'), max_length=32),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='time_deadline_response',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='time_receive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='time_submit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
