# Generated by Django 4.2 on 2023-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0038_alter_inquiry_description_alter_inquiry_number_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='state',
            field=models.CharField(blank=True, choices=[('canceled', 'انصراف'), ('waiting_for_price', 'در انتظار قیمت'), ('price_recorded', 'قیمت ارسال شده')], default='waiting_for_price', max_length=32),
        ),
    ]
