# Generated by Django 4.2 on 2023-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_alter_inquiry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='number_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
