# Generated by Django 4.2 on 2023-12-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0040_alter_inquiry_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mass_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
