# Generated by Django 4.2 on 2024-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0041_alter_project_mass_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_cover',
            field=models.ImageField(default='/static/frontend/images/colors/bg-creamy.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
