# Generated by Django 4.2 on 2024-01-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0042_project_image_cover_project_progress_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='sender',
            new_name='task_master',
        ),
        migrations.RenameField(
            model_name='taskmaster',
            old_name='title',
            new_name='name',
        ),
    ]
