# Generated by Django 4.2 on 2024-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0043_rename_sender_inquiry_task_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state_modify_time',
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('finished', 'انجام شد'), ('progress', 'در حال انجام'), ('queue', 'در صف'), ('hold', 'نگه داشته شده'), ('need-to-check', 'نیاز به بررسی'), ('need-to-replan', 'نیاز به برنامه ریزی مجدد')], max_length=20),
        ),
    ]
