# Generated by Django 4.2 on 2024-01-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0046_taskstatus_department_alter_project_time_start'),
    ]

    operations = [
    ]
