# Generated by Django 4.2 on 2024-01-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0048_alter_project_time_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',)},
        ),
    ]
