# Generated by Django 4.2 on 2024-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0049_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prepayment_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
