# Generated by Django 4.2 on 2024-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0053_remove_task_work_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiryfile',
            old_name='departments',
            new_name='to_departments',
        ),
        migrations.AlterField(
            model_name='inquirystatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید شده'), ('rejected', 'رد شده')], max_length=20),
        ),
    ]
