# Generated by Django 4.2 on 2024-01-27 22:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0054_rename_departments_inquiryfile_to_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='inquiryfile',
            name='file',
        ),
        migrations.AddField(
            model_name='inquiryfile',
            name='files',
            field=models.ManyToManyField(to='public.file'),
        ),
    ]
