# Generated by Django 4.2 on 2024-01-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0057_inquiryfile_allocator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
