# Generated by Django 4.2 on 2024-01-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0058_taskmaster_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_cover',
        ),
    ]
