# Generated by Django 4.2 on 2024-01-29 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0059_remove_project_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='allocator_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
