# Generated by Django 4.2 on 2024-01-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0061_projectnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnote',
            options={'ordering': ('id',)},
        ),
    ]
