# Generated by Django 4.2 on 2024-01-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0062_alter_projectnote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnote',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('person_traffic', models.CharField(choices=[('person/day', 'نفر/روز'), ('person/hour', 'نفر/ساعت')], max_length=15)),
                ('plan', models.IntegerField()),
                ('actual', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
