# Generated by Django 4.2 on 2024-01-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0063_alter_projectnote_options_projectstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstep',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
