# Generated by Django 4.2 on 2024-01-31 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0064_projectstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstep',
            name='from_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.department'),
            preserve_default=False,
        ),
    ]
