# Generated by Django 4.2 on 2024-03-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_projectcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='prepayment_datetime',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
    ]
