# Generated by Django 4.2 on 2024-05-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_remove_task_file_projectfile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='to_departments',
            field=models.ManyToManyField(related_name='departments_access', to='public.department'),
        ),
    ]
