# Generated by Django 4.2 on 2024-02-07 02:50

import core.mixins
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(default=0)),
                ('register_time', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.department')),
                ('register_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.itemwarehouse')),
            ],
            options={
                'ordering': ('-id',),
            },
            bases=(core.mixins.RemoveOldFileMixin, models.Model),
        ),
    ]
