# Generated by Django 4.1 on 2023-08-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_materialquality_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialitem',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='materialitem',
            name='amount_allocated',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='amount_withdrawable',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='receiver',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='time_enter',
            field=models.DateField(default='2020-4-4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialitem',
            name='time_leave',
            field=models.DateField(default='2020-4-4'),
            preserve_default=False,
        ),
    ]
