# Generated by Django 4.1 on 2023-08-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_materialitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialquality',
            name='material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialItem',
        ),
        migrations.DeleteModel(
            name='MaterialQuality',
        ),
    ]
