# Generated by Django 4.1 on 2023-08-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_materialqualityproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
