# Generated by Django 4.1 on 2023-08-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_projectfile'),
        ('warehouse', '0011_materialitem_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_status', models.BooleanField()),
                ('items', models.ManyToManyField(to='warehouse.materialitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
