# Generated by Django 4.1 on 2023-08-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_projectfile'),
        ('warehouse', '0012_materialproject_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.project'),
        ),
    ]
