# Generated by Django 4.1 on 2023-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_alter_materialproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialproject',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
