# Generated by Django 4.2 on 2024-02-01 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0065_projectstep_from_department'),
        ('warehouse', '0015_registrationfile_warehouseregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(default=0)),
                ('register_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_registrations', to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='registrationfile',
            name='warehouse_register',
        ),
        migrations.DeleteModel(
            name='WarehouseRegistration',
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='register_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.registrationwarehouse'),
            preserve_default=False,
        ),
    ]
