# Generated by Django 4.2 on 2024-02-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0065_projectstep_from_department'),
        ('warehouse', '0016_registrationwarehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(default=0)),
                ('register_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.RenameModel(
            old_name='RegistrationFile',
            new_name='ItemFile',
        ),
        migrations.DeleteModel(
            name='RegistrationWarehouse',
        ),
        migrations.AlterField(
            model_name='itemfile',
            name='register_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.itemwarehouse'),
        ),
    ]
