# Generated by Django 4.2 on 2024-02-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_itemwarehouse_rename_registrationfile_itemfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwarehouse',
            name='name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
