# Generated by Django 4.2 on 2024-02-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_itemwarehouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwarehouse',
            name='register_time',
            field=models.DateField(),
        ),
    ]
