# Generated by Django 4.2 on 2024-02-02 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0065_projectstep_from_department'),
        ('warehouse', '0019_alter_itemwarehouse_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfile',
            name='from_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.department'),
            preserve_default=False,
        ),
    ]
