# Generated by Django 4.2 on 2024-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_itemfile_from_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
