# Generated by Django 4.1 on 2023-08-17 00:09

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0010_project_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
                ('type_payment', models.CharField(choices=[('deposit', 'واریزی'), ('payment', 'پرداختی')], max_length=20)),
                ('price', models.BigIntegerField()),
                ('tracking_code', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
                ('type_payment', models.CharField(choices=[('deposit', 'واریزی'), ('payment', 'پرداختی')], max_length=20)),
                ('price', models.BigIntegerField()),
                ('tracking_code', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
