# Generated by Django 4.2 on 2023-11-24 17:43

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_alter_inquiry_state'),
        ('financial', '0002_payment_submited_at_prepayment_submited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuretyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_file_src)),
                ('number_id', models.CharField(blank=True, max_length=32, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surety_bonds', to='public.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
