# Generated by Django 4.2 on 2023-11-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_alter_inquiry_state'),
        ('financial', '0003_suretybond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suretybond',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surety_bond', to='public.project'),
        ),
    ]
