# Generated by Django 4.2 on 2023-11-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_suretybond_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='suretybond',
            name='reminder_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
