# Generated by Django 4.2 on 2024-02-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0065_projectstep_from_department'),
        ('financial', '0005_suretybond_reminder_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='suretybond',
            name='is_free',
        ),
        migrations.AddField(
            model_name='payment',
            name='type_status_payment',
            field=models.CharField(choices=[('deposit', 'واریزی'), ('payment', 'پرداختی')], default='payment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suretybond',
            name='status',
            field=models.CharField(choices=[('free', 'ازاد'), ('restricted', 'قفل')], default='free', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_payment',
            field=models.CharField(choices=[('prepayment', 'پیش پرداخت'), ('payment', 'پرداخت')], max_length=20),
        ),
        migrations.AlterField(
            model_name='suretybond',
            name='number_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='suretybond',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.project'),
        ),
        migrations.DeleteModel(
            name='PrePayment',
        ),
    ]
