# Generated by Django 4.2 on 2024-02-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_reminderproject_remove_suretybond_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
