# Generated by Django 4.2 on 2024-02-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_payment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suretybond',
            name='reminder_time',
        ),
    ]
