# Generated by Django 4.2 on 2024-02-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_remove_suretybond_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suretybond',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
